import { Box } from "@mui/material";
import Head from "next/head";

export const Header = () => {
 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <Box
    sx={{
     padding: 2,
     border: "1px solid orange",
    }}
   >
    <h1>Header</h1>
   </Box>
  </>
 );
};
